<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="c607c6cae478" failures="1" tests="3" name="user-mike" time="5.294" errors="0" timestamp="2024-01-26T17:55:33 GMT">
  <testcase classname="com.example.tests.vendorportal.VendorPortalTest" name="loginTest" time="0.665"/>
  <testcase classname="com.example.tests.vendorportal.VendorPortalTest" name="dashboardTest" time="2.087">
    <failure type="java.lang.AssertionError" message="expected [8] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [10]
at com.example.tests.vendorportal.VendorPortalTest.dashboardTest(VendorPortalTest.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dashboardTest -->
  <testcase classname="com.example.tests.vendorportal.VendorPortalTest" name="logoutTest" time="0.0">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- user-mike -->
